spring.application.name=ChatApplication
# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/chat_db
spring.datasource.username=java_user
spring.datasource.password=Vivek@2004

# Hibernate (ORM) Settings
# 'update' automatically creates/updates your database tables based on your Java models
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#JWT
jwt.secret=abe29797a8d89592b366fe428e27c342